let ids=[101,102,103,104,105]
console.log(ids)
let one=ids.pop()
console.log(ids)
let two=ids.pop()
console.log(ids)
let three=ids.pop()
console.log(ids)
let four=ids.pop()
console.log(ids)
let five=ids.pop()
console.log(ids)
console.log(one)
console.log(two)
console.log(three)
console.log(four)
console.log(five)